"use client";

import { CheckCircle2, Download, Printer, Share2 } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { format } from "date-fns";

export function ReceiptView({ payment }: { payment: any }) {
  const brandColor = payment.tenant.brand_color || "#10b981";

  const handlePrint = () => {
    window.print();
  };

  return (
    <div className="max-w-2xl mx-auto p-4 sm:p-8 space-y-6 print:p-0 print:space-y-0">
      {/* Action Bar - Hidden in Print */}
      <div className="flex items-center justify-between print:hidden">
        <h2 className="text-xl font-bold text-slate-900">Payment Receipt</h2>
        <div className="flex gap-2">
          <Button variant="outline" size="sm" onClick={handlePrint} className="rounded-xl gap-2">
            <Printer className="w-4 h-4" />
            Print
          </Button>
          <Button size="sm" className="rounded-xl gap-2 bg-emerald-600 hover:bg-emerald-700">
            <Download className="w-4 h-4" />
            Download
          </Button>
        </div>
      </div>

      {/* Main Receipt Card */}
      <Card className="relative overflow-hidden border-0 shadow-2xl rounded-[2rem] print:shadow-none print:border print:rounded-none">
        {/* Decorative Top Bar */}
        <div 
          className="h-3 w-full" 
          style={{ backgroundColor: brandColor }}
        />
        
        <div className="p-8 sm:p-12 space-y-10">
          {/* Header */}
          <div className="flex flex-col sm:flex-row justify-between items-start gap-6">
            <div className="space-y-4">
              {payment.tenant.logo_url ? (
                <img src={payment.tenant.logo_url} alt={payment.tenant.name} className="h-12 w-auto" />
              ) : (
                <div className="text-2xl font-black italic tracking-tighter" style={{ color: brandColor }}>
                  AGAPAY
                </div>
              )}
              <div>
                <h1 className="text-lg font-bold text-slate-900 uppercase tracking-tight">{payment.tenant.name}</h1>
                <p className="text-xs text-slate-500 font-medium">{payment.tenant.region || "Philippines"}</p>
              </div>
            </div>
            <div className="text-right sm:text-right w-full sm:w-auto">
              <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-emerald-50 text-emerald-700 text-[10px] font-bold uppercase tracking-widest mb-2">
                <CheckCircle2 className="w-3 h-3" />
                Verified Payment
              </div>
              <p className="text-sm font-bold text-slate-900">#{payment.payment_reference}</p>
              <p className="text-xs text-slate-500">{format(new Date(payment.verified_at || payment.submitted_at), "MMMM d, yyyy")}</p>
            </div>
          </div>

          <hr className="border-slate-100" />

          {/* Member Info */}
          <div className="grid grid-cols-2 gap-8">
            <div className="space-y-1">
              <p className="text-[10px] font-bold text-slate-400 uppercase tracking-widest">Received From</p>
              <p className="font-bold text-slate-900">{payment.loan.user.name}</p>
              <p className="text-xs text-slate-500">{payment.loan.user.email}</p>
            </div>
            <div className="space-y-1 text-right">
              <p className="text-[10px] font-bold text-slate-400 uppercase tracking-widest">Loan Reference</p>
              <p className="font-bold text-slate-900">{payment.loan.loan_reference || `LOAN-${payment.loan_id}`}</p>
              <p className="text-xs text-slate-500">Tier: {payment.loan.tier || "Standard"}</p>
            </div>
          </div>

          {/* Payment Details */}
          <div className="bg-slate-50/50 rounded-3xl p-8 space-y-6">
            <div className="flex justify-between items-center">
              <span className="text-sm font-medium text-slate-600">Payment Method</span>
              <span className="text-sm font-bold text-slate-900">{payment.payment_method.provider_name}</span>
            </div>
            <div className="flex justify-between items-center text-3xl sm:text-4xl">
              <span className="font-bold text-slate-900">Total Paid</span>
              <span className="font-black tracking-tighter" style={{ color: brandColor }}>
                ₱{Number(payment.amount_paid).toLocaleString()}
              </span>
            </div>
          </div>

          {/* Footer Note */}
          <div className="text-center space-y-4">
            <div className="flex justify-center">
              <div className="w-16 h-1 w-1 rounded-full bg-slate-100" />
            </div>
            <p className="text-[10px] text-slate-400 font-medium max-w-xs mx-auto">
              This is a digital receipt generated by Agapay. No signature required. 
              Thank you for being a responsible borrower!
            </p>
            <div className="flex justify-center gap-4 text-slate-300">
              <div className="w-2 h-2 rounded-full border border-current" />
              <div className="w-2 h-2 rounded-full border border-current" />
              <div className="w-2 h-2 rounded-full border border-current" />
            </div>
          </div>
        </div>
      </Card>
      
      {/* Terms - Hidden in Print */}
      <p className="text-[10px] text-center text-slate-400 px-12 print:hidden leading-relaxed">
        If you have any questions regarding this payment, please contact {payment.tenant.name} support or reach out via the Agapay Support channel.
      </p>
    </div>
  );
}
