-- RenameIndex
ALTER INDEX "homepage_faqs_tenant_id_workflow_status_is_active_sort_order_id" RENAME TO "homepage_faqs_tenant_id_workflow_status_is_active_sort_orde_idx";

-- RenameIndex
ALTER INDEX "homepage_testimonials_tenant_id_workflow_status_is_active_sort_" RENAME TO "homepage_testimonials_tenant_id_workflow_status_is_active_s_idx";
